### ISSUE TITLE
Cannot find drawable R.drawable.test

### ISSUE THREAD

**Issue by cosic** [lzx1413/AndroidMarkerARDemo#7]
```
AndroidMarkerARDemo/androidcalibration/src/main/java/com/example/lzx1413/androidcalibration/OnCameraFrameRender.java:123: error: cannot find symbol
        final Bitmap surfaceBitmap = BitmapFactory.decodeResource(resources,R.drawable.test);
```

**Comment by lzx1413** [comment]
you can put an image named as test.xxx into the res/drawable/ folder.

**Comment by cosic** [comment]
Ok, I did. But now I have another issue

```
In file included from ../../../../src/main/cpp/MarkerDetector.hpp:26:
../../../../src/main/cpp/MarkerDetectionFacade.hpp:34:6: warning: 'auto_ptr<MarkerDetectionFacade>' is deprecated [-Wdeprecated-declarations]
std::auto_ptr<MarkerDetectionFacade> createMarkerDetection(CameraCalibration calibration);
     ^
/Users/cosic/src/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward/auto_ptr.h:281:7: note: 'auto_ptr<MarkerDetectionFacade>' has been explicitly marked deprecated here
    } _GLIBCXX_DEPRECATED;
```

**Comment by lzx1413** [comment]
I think you can replace auto_ptr with unique_ptr as the gcc suggested, it is a c++ warning of deprecation of auto_ptr

**Comment by cosic** [comment]
Yep! It helped. But now I've had a new problem again. 

```
Process: com.example.lzx1413.androidcalibration, PID: 22225
      java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.example.lzx1413.androidcalibration.CameraCalibrator.isCalibrated()' on a null object reference
          at com.example.lzx1413.androidcalibration.MainActivity.onPrepareOptionsMenu(MainActivity.java:136)
          at android.app.Activity.onPreparePanel(Activity.java:3163)
          at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:645)
          at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:1003)
          at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:262)
          at android.os.Handler.handleCallback(Handler.java:751)
          at android.os.Handler.dispatchMessage(Handler.java:95)
          at android.os.Looper.loop(Looper.java:154)
          at android.app.ActivityThread.main(ActivityThread.java:6121)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

The `mCalibrator ` hasn't  initialized yet into `onPrepareOptionsMenu` method. I'm using Google Pixel.   As far as I guess I can solve that problem myself. Thx for helping to me.
